[package]
name = "hyakuman_no_kiseki"
version = "0.1.0"
authors = ["SAPikachu <sapikachu@gmail.com>"]

[dependencies]
env_logger = "*"
log = "*"

[dependencies.mioco]
git = "https://github.com/dpc/mioco.git"

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"
